import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Banner from '../components/banner'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Coffe Connosi</h1>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={() => console.info('a')}
        />
      </main>
    </div>
  )
}

export default Home
